// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package tracker

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfKeyT struct {
	_        structs.HostLayout
	Pid      uint32
	Ifindex  uint32
	Port     uint16
	Family   uint16
	Protocol uint8
	Pad      [3]uint8
	Daddr    [16]uint8
}

type bpfSockInfoT struct {
	_        structs.HostLayout
	Ptr      uint64
	Protocol uint32
	_        [4]byte
}

type bpfTrafficT struct {
	_       structs.HostLayout
	TxBytes uint64
	RxBytes uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapSockMap              = "sock_map"
	bpfMapTrafficMap           = "traffic_map"
	bpfProgKprobeTcpRecvmsg    = "kprobe_tcp_recvmsg"
	bpfProgKprobeTcpSendmsg    = "kprobe_tcp_sendmsg"
	bpfProgKprobeUdpRecvmsg    = "kprobe_udp_recvmsg"
	bpfProgKprobeUdpSendmsg    = "kprobe_udp_sendmsg"
	bpfProgKretprobeTcpRecvmsg = "kretprobe_tcp_recvmsg"
	bpfProgKretprobeUdpRecvmsg = "kretprobe_udp_recvmsg"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeTcpRecvmsg    *ebpf.ProgramSpec `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg    *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpRecvmsg    *ebpf.ProgramSpec `ebpf:"kprobe_udp_recvmsg"`
	KprobeUdpSendmsg    *ebpf.ProgramSpec `ebpf:"kprobe_udp_sendmsg"`
	KretprobeTcpRecvmsg *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_recvmsg"`
	KretprobeUdpRecvmsg *ebpf.ProgramSpec `ebpf:"kretprobe_udp_recvmsg"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	SockMap    *ebpf.MapSpec `ebpf:"sock_map"`
	TrafficMap *ebpf.MapSpec `ebpf:"traffic_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	SockMap    *ebpf.Map `ebpf:"sock_map"`
	TrafficMap *ebpf.Map `ebpf:"traffic_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.SockMap,
		m.TrafficMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeTcpRecvmsg    *ebpf.Program `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg    *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpRecvmsg    *ebpf.Program `ebpf:"kprobe_udp_recvmsg"`
	KprobeUdpSendmsg    *ebpf.Program `ebpf:"kprobe_udp_sendmsg"`
	KretprobeTcpRecvmsg *ebpf.Program `ebpf:"kretprobe_tcp_recvmsg"`
	KretprobeUdpRecvmsg *ebpf.Program `ebpf:"kretprobe_udp_recvmsg"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeTcpRecvmsg,
		p.KprobeTcpSendmsg,
		p.KprobeUdpRecvmsg,
		p.KprobeUdpSendmsg,
		p.KretprobeTcpRecvmsg,
		p.KretprobeUdpRecvmsg,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
